index.html

Blockies is a tiny library for generating blocky identicons.
It can be useful to generate sprites.

Add Blockies

---

index.html

* Update broken link of `ox - a tiny 2D game framework for the web`
* Added 3 news resources at Artwork and fonts section

Update broken link & new resources

---

index.html

Remove empty link

---

index.html

Added "glitch torpedo" post mortem

---

index.html

Added Phosphorus Dating postmortem to the resource list.

added Phosphorus Dating postmortem

---

index.html

https://github.com/voronianski-on-games/js13kGames-boilerplate
>  Minimum game starter kit includes game loop, utility functions and webpack configuration to package game with just one command.

Add js13kGames-boilerplate to resources

---

index.html

Adds a boilerplate I've been working on that I've been sharing with some friends.

adds yet another boilerplate

---

index.html

(you can remove the 3 other minifiers too if you want, they're less good than babeljs)

babeljs minifier

---

index.html

r? @end3r 
Some initial A-Frame resources. Once they're in, I'll ask the A-Frame slack to expand.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/js13kgames/resources/35)

Initial A-Frame resources

---

index.html

Submitting a postmortem for my JS13k 2017 entry.

Add Lost In Labyrinth Postmortem to 2017 list

---

index.html

Adding the story behind http://js13kgames.com/entries/scribble

Add Scribble to 2017 post-mortem list

---

index.html

Per request at https://twitter.com/js13kGames/status/908267327564783616

Add Adrift to 2017 post-mortem list

---

index.html

Adding more resource tools to the code

Adding more tools

---

index.html

(postmortem is in the README of the github project)

add AMAZ3D postmortem

---

index.html

Thanks for the email reminder Andrzej.

Add Fly South (2017) post-mortem

---

index.html

The contest introductory video by its organizer

Included an youtube video link

---

index.html

I fixed the link to my blog post as I have restructured my site.

Fix the link to my blog post

---

index.html

Hello! Wanted to share a repo I put together that uses parcel to build, zip, and check the file size of a project.

Add js13k-parcel-starter to the list of resources

---

index.html

Hello! I Wanted to share a repo to compile, minify, inline and zip games, to improve weight optimization of games.

Added gulp boilerplate stater

---

index.html

Like it says in the title! /cc @braddunbar

ONOFF Post Mortem by Daniel Marino

---

index.html

I've added my article about creating game [Hoverla]

add Hoverla post-mortem article

---

index.html

Added post-mortem of Earth that was

Added post-mortem of Earth that was

---

index.html

Added post-mortem for **When my vpn goes offline it allows all kinds of people to snoop on my computer, such as demons...**

Added post-mortem for When My VPN Goes Offline

---

index.html

A new bullet in the list of game engines with link to "floppy" game engine.

Adding link to "floppy" micro game engine 

---

index.html

As we talked, here is the reference to A-Frame boilerplate

Added A-Frame boilerplate reference

---

index.html

SpriteStack is really interesting, based on the sprite stacking technique to create appearances of 3D models from several slices of sprites.

Include SpriteStack

---

index.html

Lightweight and beginner friendly micro engine.

added my engine github.io link

---

index.html

Add Backflipped postmortem

---

index.html

My post mortem is mostly about game concept design.

Add my post mortem blog to the resources

---

index.html

I wrote a second postmortem, I hope it's OK. This one is more about technical implementation details, while the previous was more about game design.

Add my second postmortem to the resources

---

index.html

If possible, please could you add this link to the bottom of my game description page too? Thank you.

Add write-up for Get Back From Robot City

---

index.html

Just posted a Webpack TypeScript project to GitHub tonight that might be handy for folks.

Include a Webpack TypeScript start project

---

index.html

First 2020 postmortem!
https://github.com/codyebberson/js13k-minipunk#postmortem

Added Minipunk 2020 postmortem

---

index.html

Created a postmortem for my JS13K entry, so adding it to the resources page.

Added "Planet not found" postmortem

---

index.html

Made a mistake when updating the postmortem, sorry about that.

Fix closing link tag

---

index.html

Adding my postmortem in a medium story link.

Added my "Employee not Found" postmortem.

---

index.html

Add Flow of Four postmortem

---

index.html

Also fixes link to Rhythm Not Found postmortem

Add link to Island Not Found postmortem

---

index.html

Adding 2 resources:
- a micro-framework that I've developed over the last 3 years participating in JS13KGAMES
- an article I wrote for Net Mag/Creative Bloq explaining 6 technics to detect, react and control screen orientation on mobile devices, complete with code samples, a video and links to Codepen examples.

Add 'gamejam-boilerplate' micro framework and 'How to master screen orientation' tutorial

---

index.html

Add Vote by Mail blog post to resources

---

index.html

Added Using Emojis in a Point and Click Adventure article to 2020 section.

Added Using Emojis in a Point and Click Adventure article to 2020 section

---

index.html

Add post mortem entry of my game, Black Jack 404, https://js13kgames.com/entries/black-jack-404.

Post mortem entry

---

index.html

Adds ZzFXM to the resource list for 202

Add making of ZzFXM to the resources page

---

index.html

Added it below postmortems, as it's not a postmortem. I've already written one earlier.

Added post on using js_of_ocaml for js13k

---

index.html

I've linked to my dev diaries for my two entries to JS13k 2021

Added dev diaries for my entries to JS13k 2021

---

index.html

adding in subspace zero post mortem for 2021 js13k :)

Added Subspace Zero - Alex Delderfield

---

index.html

Added a link to my postmortem on SPACE Saver. The little game where you clear space, for space ships.

Added my postmortem link.

---

index.html

Also add my twitter handle to past postmortems (6 years already!)

Add 2021: a Space Opera postmortem

---

index.html

I've resumed work on Craters and updated the link to reflect the project's new name.

I've fixed a broken link and added a new description to it.

---

index.html

Link to the jsfiddle with code.

Generate nice galaxy background link

---

index.html

I've added a link to my dev diary to the resources page, I'll add some postmortem notes once I've caught up on my sleep

Added devdiary/postmortem for Bee Kind

---

index.html

Added my post mortem to the 2022 list

Update index.html to include Charon Jr. post mortem

---

index.html

- Add post-mortem for my game, Death Estate

Add Death Estate post-mortem

---

index.html

- Add *Moth* post-mortem to list for 2022.

Add Moth post-mortem

---

index.html

Fixed some indent issues and added a link to Soul Jumper Post Mortem

Added Soul Jumper post-mortem

---

index.html

Adding Gravepassing to the list of 2022 postmortems.

Adding 2022 post mortem

---

index.html

Adds the link to Dante post mortem

Dante's post-mortem

---

index.html

* Added links to my TypeScript starter projects. One has built-in support for WebGL, the other uses regular 2d canvas.

Add TypeScript Starters

---

index.html

My blog has moved, so I need to update the link to my 2021 post-mortem.

Update link to 2021 post-mortem

---

index.html

Add post mortem of my game, Samurai Sam: https://js13kgames.com/entries/samurai-sam

docs: add post mortem, Samurai Sam

---

index.html

Adds my 2023 postmortem.
Also, updates my contact information in my two older articles since I don't use twitter much anymore.

Add my 2023 postmortem

---

index.html
style.css

Adds the link to last years competition, but reduces the font size to 16px.

Add link to 2022 comp page

---

index.html

Hi,
Sending this PR just to add my post mortem for 2023 edition.
Thanks!

added isacben's js13kgames 2023 post mortem entry

---

index.html

Postmortem is the readme for the game's repo. Thanks!

Adding Robin of Thirteensley 2023 postmortem

---

index.html

Hi, this is a PR for my entry Post mortem (Cathedral builder)
Thanks

Cathedral builder post mortem

---

index.html

Death Sea XIII game post mortem

add: death sea post mortem

---

index.html

Updated index.html to include post-mortem link for 'Bewitched!'

adds 2023 post-mortem entry for Bewitched!

---

index.html

My new pixelart editor allows saving multiple projects and remembers your palette. It supports both color formats `#FFF` and `#FFFFFF`, and icons can have different sizes.

Add my new mini pixelart editor to the resources

---

index.html

https://blog.cassidoo.co/post/thirteen-potions/

Add Thirteen Potions to 2023 post mortems

---

index.html

add 3 links

---

README.md

Adding link to post-mortem for 'Gecko Blaster'

Added post-portem for "Gecko Blaster"

---

README.md

I've released a new version of the pixel art editor, and split it into image editor and font editor. The image editor has new features and the font editor is completely new.

Add pixel font editor and updates pixe image editor

---

README.md

Gotchas while developing a tiny web game 
https://dev.to/lopis/gotchas-while-developing-a-tiny-web-game-4528

Add postmortem

---

README.md

Post Mortem posted in the README section

Update README.md with wands of triskaidekai post-mortem

---

README.md

Adds Spirit Hunter post-mortem to the list.

Add Spirit Hunter to resources, README.md

---

README.md

Add 13s post-mortem and ant-ecs architecture

Add postmortem and eCS

---

README.md

changed thinky description to be more specific

thinky description

---

README.md

Half postmortem, half general article, about this years comp

Meow Mountain porstmortem
